# Generated by Django 5.2 on 2025-04-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0007_remove_uploadedfile_torrent_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='torrent_file',
            field=models.FileField(blank=True, null=True, upload_to='torrents/'),
        ),
    ]
