# Generated by Django 5.2 on 2025-04-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0011_uploadedfile_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='seed_count',
            field=models.IntegerField(default=0),
        ),
    ]
