# Generated by Django 5.2 on 2025-04-30 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0012_uploadedfile_seed_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='seed_count',
        ),
        migrations.DeleteModel(
            name='DownloadHistory',
        ),
    ]
