# Generated by Django 5.2 on 2025-04-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0005_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='magnet_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='torrent_file',
            field=models.FileField(blank=True, null=True, upload_to='torrents/'),
        ),
    ]
