# Generated by Django 5.2 on 2025-04-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0006_uploadedfile_magnet_link_uploadedfile_torrent_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='torrent_file',
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Assignment', 'Assignment'), ('Multimedia', 'Multimedia'), ('Slide', 'Slide'), ('QA', 'QA')], default='Books', max_length=50),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='seeder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='torrent_hash',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
