# Generated by Django 5.2 on 2025-04-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0008_uploadedfile_torrent_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadedfile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='magnet_link',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='seeder_count',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='torrent_file',
        ),
        migrations.RemoveField(
            model_name='uploadedfile',
            name='torrent_hash',
        ),
    ]
