# Generated by Django 5.1.7 on 2025-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0018_studentprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='thumbnail',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
